source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ImageViewer' do
    pod 'Alamofire', '~> 4.5'
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'PopupDialog', '~> 0.7'
end
